# Site settings
title: Muhammad Ibnu
description: Mahasiswa Sistem Informasi
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Muhammad Ibnu
user_description: Nama saya Muhammad Ibnu, Saya kuliah di UIN SUSKA RIAU Program Studi Sistem Informasi semester VII Fakultas Sains dan Teknologi
user_title: Mahasiswa Sistem Infomasi
email: ibnu.muhammad27@gmail.com
linkedin: Muhammad Ibnu
github_username:  muhammadibnu46
gplus_username:  ibnu.muhammad27@gmail.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
